apiVersion: v1
kind: Template
metadata:
  name: package-extract-imagestream
  annotations:
    description: This is Thoth Core - Package Extract ImageStream
    openshift.io/display-name: "Thoth: Package Extract ImageStream"
    version: 0.1.3
    tags: poc,thoth,ai-stacks,package-extract
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth Package
      Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: package-extract-imagestream
    app: thoth
    component: package-extract

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
        component: package-extract
      name: package-extract
    spec:
      name: latest
      lookupPolicy:
        local: true
